const ctbPhrases = [
  'Elle est énorme cette file d\'attente...',
  'J\'adore cette musique, même si elle est un peu longue...',
  'L\'océan, ça sent quand même un peu la mer...',
  'Cette sauce a une longueur en bouche intéressante...',
  'C\'est dommage que ce roman soit si court...',
  'Mais il est tout petit ce canari...',
  'Ce broccoli a vraiment un sale goût...',
  'Je vais avaler cette glace d\'un coup...',
  'Ce film était très bien, mais un peu court...',
  'Ça sent le poisson pourri cette histoire...',
  'La carte est immense...',
  'Ce chaton est vraiment trop mignon...',
  'Il arrive toujours par derrière cet ennemi...',
  'La souris peut largement passer par ce minuscule trou...',
  'Je pense que ça peut passer...',
  'Même en forçant, ça passera jamais...',
  'Il est pas beau ce portail...',
  'Il est magnifique ce lampadaire...',
  'Ce repas m\'a laissé une sensation merveilleuse dans la bouche...',
  'Elle est amère, cette bière...',
  'Cette étoffe est douce et soyeuse...',
  'Il faudrait qu\'elle prenne l\'air plus souvent...',
  'Ça sent le renfermé...',
  'Cette fleur émet un parfum floral...',
  'Jouer à ce jeu ne me procure plus aucun plaisir...',
  'Jardiner me procure énormément de plaisir...',
  'Ces paysages sont très impressionnants...',
  'Il a un égo surdimensionné...',
  'Cette soupe est très goûtue...',
  'Le Grand Canyon est colossal...',
  'Elle a les chevilles qui enflent...',
  'Vis à vis de la situation, c\'était une réaction démesurée...',
  'Cette cathédrale est monumentale...',
  'Ce château est immense et somptueux...',
  'Les bactéries sont microscopiques...',
  'Les microbes ne sont pas visibles à l\'oeil nu...',
  'Ce concombre est tout rabougri, il fait peine à voir...',
  'Ce fichier est volumineux...',
  'Ce vase de l\'époque Ming a une valeur inestimable...',
  'Cette histoire est tout bonnement incroyable...',
  'Il en faut peu pour être heureux...',
  'J\'ai hâte qu\'elle s\'en aille...',
  'Elle a grandi si vite...',
  'Cet homme est très petit, mais très sage...',
  'Ce mécanisme est rudement efficace...',
  'A ce jour, l\'épave de la Cordelière reste introuvable...',
  'Ça fait un bail qu\'on ne l\'a plus aperçue...',
  'Il y a longtemps qu\'elle n\'est plus sortie de chez elle...',
  'Cet exercice est beaucoup trop dur pour moi...',
  'Ce gâteau est ferme et fondant...',
  'Il a des muscles saillants et fermes...',
  'Habillé comme ça, il a vraiment l\'air ridicule...',
  'Cet arbre se dresse majestueusement au milieu de l\'allée...',
  'La statue a été érigée en l\'honneur de son père...',
  'Ce joueur possède une agilité exceptionnelle...',
  'Cette joueuse dipose d\'une endurance à toute épreuve...',
  'Malheureusement, elle n\'a pas la bonne taille...',
  'Il est beaucoup trop petit pour elle...',
  'Elle est beaucoup trop grande pour lui...',
  'Jamais elle ne reverra la lumière du jour...',
  'Son goût est subtil et délicat...',
  'Le parfum de cet homme est écoeurant...',
  'J\'aimerai bien la voir en vrai, un jour...',
  'Elle a connu des jours meilleurs...',
  'C\'est tellement bon qu\'on en mangerait...',
  'Un tien vaut mieux que deux tu l\'auras...',
  'Pour un fruit aussi coloré, c\'est vraiment très fade...',
  'Ce plat a une sucrosité intéressante...',
  'Cette viande est vraiment tendre à souhaite...',
  'Sa voix est douce et voluptueuse...',
  'Sa voix est suave et envoûtante...',
  'Sa voix est ferme et rocailleuse...',
  'Le chocolat a fondu dans ses mains...',
  'Ce blanc de poulet fond en bouche...',
  'Il est parti en me laissant une sensation désagréable...',
  'Cette idée m\'emplit de joie et d\'allégresse...',
  'Son regard me remplit de tristesse et d\'amertume...',
  'La route est longue et sinueuse...',
  'Elle me va comme un gant, cette couleur...',
  'Décidemment, on arrivera jamais à faire rentrer le piano dans le camion...',
  'L\'escalier est trop étroit, ça ne passera jamais...',
  'Le tapis est resté dehors toute la nuit, il est très rigide et très froid...',
  'Si tu veux survivre, il faut t\'endurcir...',
  'Elle a un caractère bien trempé...',
  'Cet homme dégage une aura malveillante...',
  'C\'est vraiment très tentant...',
  'Ce n\'est pas tentant du tout...',
];

const characters = {
  SPELUNKY: ['Ana', 'Margaret', 'Colin', 'Alto', 'Roffy', 'Coco', 'Demi', 'Little Jay', 'Manfred', 'Liz', 'LISE', 'Nekka', 'Ayrin', 'Guy Spelunky', 'Valerie', 'Tina'],
  MORTA: ['John', 'Linda', 'Mark', 'Kevin']
};

const commandCategories = {
  TEXT:'text',
  SFX:'sfx',
  MOD:'moderation',
  MISC:'misc'
};

const modCommands = [
  '!killsfx',
  '!killsfxq'
];

const timerPhrases = [
  "Envie de voir ou revoir des clips, avoir les dernières infos sur la chaîne ou simplement discuter ? Rejoins le discord : https://discord.gg/PaZbKcX !",
  // "Des changements concernant le système d'XP ont été annoncés sur le Discord, des récompenses à la clé : https://discord.gg/PaZbKcX !",
  // "Retrouve les dernières VODs et les Best Œufs sur la chaîne youtube : https://www.youtube.com/channel/UCn_cu9jENWmF2IA5Rj3DoEQ/ !",
  "🦇 Le Best Œuf #6 est enfin là : https://youtu.be/jIVrpZDWLU0 🎅 Merci à tous pour vos clips et n'hésitez pas à clip les moments du live qui vous plaisent 😘",
  "🏆!top pour le classement de la saison, à la clé : un sfx personnalisé, des faveurs d'oeufrobot, votre nom dans la postérité de YouTube 🥳",
  // "💖 Live cuisine Saint-Valentin ce dimanche 14 février de 10h à midi ! Les recettes sont disponibles en avance sur le discord https://discord.gg/PaZbKcX ! 🍳"
];

const jokes = [
  "Toto mange un œuf et du jus d’orange au petit-déjeuner. Arrivé à l’école il se fait interroger par la maîtresse : – Toto récite-moi les nombres de 1 à 10 ! – 1, 2, 3, 4, 5, 6, 7, 8, 10.  – Mais Toto tu as oublié le 9 ! – Ben non madame, je l’ai mangé ce matin...",
  "C'est 2 œufs dans une poêle, y en a qui dit \"Il fait drôlement chaud ici, tu ne trouves pas ?\" et l'autre répond \"AHGRH UN ŒUF QUI PARLE !\"",
  "Dans la salle d’attente d’un vétérinaire, deux fauteuils sont respectivement occupés par une poule et par un œuf. Le vétérinaire passe la tête par l’entrebâillement de la porte et questionne : – Lequel de vous deux est arrivé le premier ?",
  "Deux œufs discutent dans un frigo : – Pourquoi t'es tout vert avec des poils ? – C'est parce que je suis un kiwi, abruti !",
  "Pourquoi les œufs viennent-ils à la messe avec du savon ? Pour l’Ave Maria.",
  "Comment reconnaît-on un œuf dans un aéroport ? C’est le seul qui donne du pain aux avions.",
  "Pourquoi les œufs enlèvent-ils leurs lunettes lorsqu'ils font un alcootest ? Parce que ça fait toujours deux verres en moins.",
  "À quoi reconnaît-on un œuf sur les berges de la Seine ? C’est le seul qui vaporise de l’insecticide sur les bateaux-mouches !",
  "Qu'est-ce qu'un squelette dans un placard ? C’est un oeuf qui a gagné à cache-cache.",
  "Pourquoi les oeufs vont-ils dans le désert avec une fenêtre ? Pour pouvoir l’ouvrir s’ils ont trop chaud.",
  "Pourquoi les oeufs n'ont pas de glaçons ? Ils ont perdu la recette.",
  "Qui a inventé les sous-marins ? Les oeufs en essayant de construire un bateau.",
  "Que faire lorsqu'un belge vous lance une grenade ? La dégoupiller et lui renvoyer.",
  "Un homme rentre chez le coiffeur. Celui-ci lui demande : - Je vous fais un shampooing aux oeufs ? - Non, non, à la tête comme d'habitude",
  "Monsieur et Madame Deuf ont un fils, comment s'appelle-t-il ? John",
  "Melon et Melèche veulent faire des crêpes. Melon achète la farine et Melèche les oeufs.",
  "Est-ce qu'une poule peut parler anglais ? Yes chicken !",
  "Un jour, Dieu ordonna à David de guetter... et David Guetta !",
  "C’est l'histoire d’un oeuf qui respire par les fesses. Un jour il s'assied, et il meurt.",
  "Pourquoi les oeufs sont-ils moins chiants en février ? Parce qu'il n'y a que 28 jours.",
  "Qu'est ce qui est transparent et qui court dans les champs ? Un troupeau de vitres.",
  "Deux oeufs discutent : – Depuis quelques jours je vois des points noirs ! – Ah oui et t'as vu l’oculiste ? – Non, juste des points noirs...",
  "Quelle est la couleur du virus de la grippe ? Gris pâle.",
  "Qu'est-ce qui est plus fort qu’un oeuf ? Deux oeufs.",
  "Un jour, Dieu demanda au coca de coller... et le Coca Cola.",
  "Combien d'oeufs est-il possible de manger à jeun ? Un seul.",
  "Un jour, Dieu ordonna à Léonard de devenir une scie. Et Léonard De Vinci !",
  "Un jour, Dieu ordonna à Hélène de s'égarer... et Hélène Ségara !",
  "Un jour, Dieu ordonna à Bruce de lire... et depuis, Bruce Lee !",
  "Un jour, Dieu ordonna à Katy de mourir... et Katy Perry !",
  "Un jour, Dieu ordonna à Mara de donner... et Maradona !",
  "Un jour, Dieu ordonna à Fred d’avoir cet air... et depuis, Fred Astair !",
  "Un jour, Dieu ordonna qu'on arrête Franklin... alors on Aretha Franklin",
  "Un jour, Dieu ordonna à Nir de vanner... et Nirvana !",
  "Un jour, Dieu ordonna à Nathalie de bailler... et depuis, Nathalie Baye !",
  "Un jour, Dieu ordonna à Lady de faire un gag... et Lady Gaga !",
  "Un jour, Dieu ordonna à Benz d'aimer... et Benzéma !",
  "Un jour, Dieu ordonna à Adriana de limer... et Adriana Lima !",
  "Un jour, Dieu ordonna à Plat de tondre... et depuis, Platon !",
  "Un jour, Dieu ordonna à Kiri de coudre... et depuis, Kirikou !",
  "Un jour, Dieu ordonna à Gargan de tuer... et Gargantua !",
  "Un jour, Dieu ordonna à Lustu de croire... et Lustucru !",
  "Un jour, Dieu ordonna au riz de coller... et le Ricola !",
  "Un jour, Dieu ordonna à Rex de sonner... et Rexona !",
  "Un jour, Dieu ordonna à Goo de gueuler... et depuis, Google !",
  "Un jour, Dieu ordonna au chaud de coller... et le chocolat !",
];

const insults = [
  "trouve que, aujourd'hui, $user ne ressemble à rien.",
  "aimerait bien rire aux blagues de $user, mais c'est il n'y arrive pas. Vraiment pas drôle.",
  "trouve que $user ressemble à une vieille serpillière malade.",
  "a l'impression que $user a pris 20 ans.",
  "n'a jamais vraiment aimé $user, comme ses parents.",
  "semble indiquer que $user est une erreur de la nature.",
  "ne peut pas voir $user en peinture.",
  "trouve $user insupportable.",
  "trouve $user hideux.",  
  "trouve que $user est une personne détestable.",
  "aimerait bien ressembler à $user. Ou pas.",
  "aimerait avoir le sens de l'humour de $user. Ou pas.",
  "n'aimerait pas passer ne serait-ce qu'une heure avec $user.",
  "ne supporte pas les caprices de $user.",
  "trouve que $user se comporte comme un bébé.",
  "n'aime pas les pleurnichards comme $user.",
  "trouve que $user n'a aucune classe.",
  "préfèrerait oublier qu'il connait $user.",
  "aimerait ne jamais avoir rencontré $user",
  "n'arrive pas à dire du bien de $user. Rien n'y fait.",
  "se sentirait mieux si $user arrêtait un peu de parler.",
  "se moque de la coupe de cheveux de $user.",
  "trouve que les habits de $user iraient mieux à un abribus.",
  "n'en peux plus de devoir discuter avec une personne aussi creuse que $user.",
  "n'arrive pas à se faire à l'idée que $user soit un être doué d'intelligence."
];

const compliments = [
  "trouve que $user est de toute beauté.",
  "trouve que $user est une personne resplendissante.",
  "trouve $user très drôle.",
  "estime que $user est vraiment la personne la plus dévouée, la plus belle, la plus drôle, la plus pétillante et la plus distinguée du monde. Bref, un être humain merveilleux.",
  "a une grande estime pour $user.",
  "pense tout le bien du monde de $user.",
  "trouve que $user est une personne très intéressante.",
  "trouve que $user est une personne fort sympatique.",
  "ferait le tour du monde pour $user.",
  "regarde amoureusement $user. Une personne géniale, vraiment !",
  "regarde $user comme si c'était le plus beau des oeufs.",
  "regarde $user avec des étoiles dans les yeux.",
  "trouve que $user est la personne la plus gentille du quartier.",
  "est de bonne humeur grâce à $user.",
  "se tord de rire en dès qu'il entend une blague de $user.",
  "n'ose pas aborder $user tellement c'est une personne charismatique et impressionnante.",
  "trouve $user incroyable.",
  "admire $user. Quelle personne fantastique !",
  "se dit que, s'il avait un sens de l'humour, il ne pourrait résister à $user.",
  "se dit que, s'il était capable d'avoir des sentiments, il tomberait probablement amoureux de $user.",
  "se dit que, s'il était québécois, il tomberait en amour de $user.",
  "se dit qu'il se ferait bien un petit resto avec $user.",
  "serait prêt à mourir pour $user.",
  "n'a d'yeux que pour $user.",
  "aime être avec $user. Il se sent apaisé.",
  "trouve que les vêtements de $user lui vont super bien.",
  "ne s'ennuie jamais avec $user.",
  "pense que $user est irremplaçable.",
  "partage beaucoup de choses avec $user. Il est en confiance.",
  "remercie $user d'exister.",
  "se dit que $user lui fait voir le monde comme personne, ni humain ni robot, ne lui a fait voir avant.",
  "trouve que $user est le meilleur amant du monde.",
  "trouve que $user a une énergie très communicative.",
  "estime que, quand il est avec $user, tout devient possible.",
  "ne peut plus vivre sans $user.",
  "estime que le monde est tellement ennuyeux sans $user.",
  "trouve que $user rend les petites choses importantes.",
  "trouve que la gentillesse de $user n'a pas de limites.",
  "pense que se reproduire avec $user serait vraiment bénéfique à l'humanité.",
  "adore les doigts de pied de $user.",
  "adore les coudes de $user.",
  "adore les genoux de $user.",
  "adore les omoplates de $user. Vraiment top.",
];

const eggPhrases = [
  "tend délicatement un œuf à $user. Prends-en soin.",
  "donne négligemment un œuf à $user. Prends-en soin.",
  "lance violemment un œuf vers $user. Prends-en soin.",
  "dépose doucement un œuf sur la tête de $user. Prends-en soin.",
  "sort un œuf d'on ne sait où et le tend $user. Prends-en soin.",
  "pond un œuf et le donne à $user. Prends-en soin.",
  "se dit qu'il garderait bien cet œuf pour lui mais le donne quand même à $user. Prends-en soin.",
  "propose tendrement un œuf à $user. Prends-en soin.",
  "lance violemment un œuf vers $user. Prends-en soin."
];

const killSFXPhrases = [
  "a pulverisé le SFX. De rien.",
  "a exterminé le SFX. De rien.",
  "a détruit le SFX. De rien.",
  "a explosé le SFX. De rien.",
  "a abattu le SFX. De rien.",
  "a écrasé le SFX. De rien.",
  "a écrabouillé le SFX. De rien.",
  "a anéanti le SFX. De rien.",
  "a désagrégé le SFX. De rien.",
  "a déchiqueté le SFX. De rien.",
  "a bousillé le SFX. De rien.",
  "a foudroyé le SFX. De rien.",
  "a vaporisé le SFX. De rien."
];

const killQueuePhrases = [
  "a exterminé la file d'attente des SFX. De rien.",
  "a pulverisé la file d'attente des SFX. De rien.",
  "a détruit la file d'attente des SFX. De rien.",
  "a explosé la file d'attente des SFX. De rien.",
  "a abattu la file d'attente des SFX. De rien.",
  "a écrasé la file d'attente des SFX. De rien.",
  "a écrabouillé la file d'attente des SFX. De rien.",
  "a anéanti la file d'attente des SFX. De rien.",
  "a désagrégé la file d'attente des SFX. De rien.",
  "a déchiqueté la file d'attente des SFX. De rien.",
  "a bousillé la file d'attente des SFX. De rien.",
  "a foudroyé la file d'attente des SFX. De rien.",
  "a vaporisé la file d'attente des SFX. De rien."
];

const connectPhrases = [
  "fait une entrée fracassante.",
  "débarque en grande pompe.",
  "arrive les doigts de pied en éventail.",
  "se connecte, prêt à en découdre.",
  "Beep bop boop. Je suis un robot.",
  "n'est jamais en retard, ni en avance d'ailleurs. Il arrive précisemment à l'heure prévue.",
  "pose ses valises dans le tchat.",
  "arrive en ville. Changez de trottoir.",
  "fait une entrée remarquée.",
  "débarque virilement dans le tchat.",
  "arrive comme un cheveu sur la soupe.",
  "se glisse discrètement dans le tchat. Circulez, y a rien à voir.",
  "roule des mécaniques. Brrr",
  "arrive timidement dans la tchat.",
  "s'assied discrètement dans un coin du tchat pour observer.",
  "est un peu en retard, mais il est bien là.",
  "est un peu en avance, on ne va pas lui en vouloir.",
  "ne semble pas dans son assiette, mais il va faire de son mieux.",
  "arrive à l'improviste. Surprise !",
  "arrive, haletant, dans le tchat.",
  "arrive pour sauver l'humanité et s'occuper du tchat. En même temps."
];

const beepboopPhrases = [
  "Beep boop",
  "Bop beep boop",
  "Beep beep burp",
  "Bleep boop",
  "Beep beep boop",
  "Boop bleep",
  "Beep bleep boop",
  "Beep boop boop",
  "Boop beep boop",
  "BOOP BEEP BOOP",
  "BEEP BEEP BOOP",
  "BOOP BEEP",
  "BEEP BOOP",
  "BOOP BLEEP BOOP",
  "BEEP BOOP BEEP",
];

const botPhrases = [
  "fixe intensément $user.",
  "approuve ce que dit $user.",
  "ne semble pas approuver ce que dit $user.",
  "n'est pas d'accord avec $user.",
  "observe attentivement $user.",
  "regarde $user d'un air réprobateur.",
  "ne dit rien, mais n'en pense pas moins.",
  "s'en lave les mains, mais d'une force...",
  "ne croit pas une seule seconde aux bobards de $user.",
  "n'y voit pas d'inconvénient.",
  "commence à fumer de manière excessive.",
  "aurait bien besoin d'un peu d'huile de moteur.",
  "regarde $user de haut (c'est un grand robot).",
  "se ferait bien une omelette. OU PAS !",
  "est toujours prêt pour la bagarre. Méfie-toi $user...",
  "est totalement d'accord avec ce que dit $user.",
  "ne comprend pas un mot de ce que $user baragouine.",
  "n'arrive pas à comprendre $user.",
  "regarde $user avec un air suspicieux.",
  "ne parvient pas à savoir si $user se moque de lui.",
  "se fiche éperduement de ce que $user peut bien lui raconter."
];

const botElitePhrases = [
  "regarde respectueusement $user.",
  "regarde amoureusement $user.",
  "observe $user. Impressionnant",
  "semble reconnaissant envers $user.",
  "aimerait bien être $user.",
  "s'incline devant $user.",
  "fantasme régulièrement sur $user.",
  "déshabille $user du regard.",
  "voudrait bien être comme $user.",
  "rampe aux pieds de $user.",
  "baisse les yeux en passant à côté de $user.",
  "veut se marier avec $user.",
  "aimerait vraiment être dans les petits papiers de $user."
];

const eliteUsers = ['synrj', 'synrj', 'synrj'];

const bots = ['streamlabs', 'lemonjuices12', 'lollyneuter', 'twitchdetails', 'vaidather', 'oeufrobot', 'wizebot', 'p1duup', 'synrj', 
'extramoar', 'gowithhim', 'electricallongboard', 'ftopayr', 'eulersobject', 'utensilzinc', 'restreambot', 'commanderroot', 'bingcortana', 
'communityshowcase', 'rubberslayer'];

const ranks = [
 { lvl: 200, name: 'L\'Œuf avec un grand Œ' },
 { lvl: 150, name: 'Futur Seigneur de Mordœuf' },
 { lvl: 100, name: 'Œuf de 100 ans' },
 { lvl: 75, name: 'Fabergœuf' },
 { lvl: 60, name: 'Adoratœuf' },
 { lvl: 50, name: 'Amourœuf' },
 { lvl: 40, name: 'Œuforique' },
 { lvl: 35, name: 'Adœufrable' },
 { lvl: 30, name: 'Œuficionado' },
 { lvl: 25, name: 'Joyœuf' },
 { lvl: 20, name: 'Nouvœuf' },
 { lvl: 15, name: 'Coquille' },
 { lvl: 1, name: 'Embryœuf' },
];

module.exports = {
  ctbPhrases,
  timerPhrases,
  killQueuePhrases,
  killSFXPhrases,
  connectPhrases,
  botPhrases,
  botElitePhrases,
  beepboopPhrases,
  modCommands,
  commandCategories,
  eliteUsers,
  jokes,
  insults,
  compliments,
  eggPhrases,
  bots,
  ranks,
  characters
};